server:
  port: 8082
spring:
  application:
    name: clientms

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      #,http://localhost:8762/eureka
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 8
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: COUNT_BASED
        waitDurationInOpenState: 30
        failureRateThreshold: 50
        minimumNumberOfCalls: 4
    instances:
      usermsclient:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransferFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED